# Generated by Django 5.2.15 on 2026-06-07 23:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovimientoEnvasado',
            new_name='Envasado',
        ),
        migrations.RemoveField(
            model_name='palet',
            name='creado',
        ),
    ]
