# Generated by Django 5.2.15 on 2026-06-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_movimientoenvasado_envasado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envasado',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='envasado',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='palet',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='produccion',
            name='tipo',
            field=models.CharField(choices=[('60', '60'), ('68', '68'), ('120', '120')], max_length=10),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='categoria',
            field=models.CharField(choices=[('buena', 'Buena'), ('mala', 'Mala'), ('especial', 'Especial')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Despacho',
        ),
        migrations.DeleteModel(
            name='Envasado',
        ),
        migrations.DeleteModel(
            name='Palet',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
