# Generated by Django 5.2.15 on 2026-06-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_despacho_palet_movimientostock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='produccion',
            name='nombre_operario',
            field=models.CharField(default='sin nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='palet',
            name='lote',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
