# Generated by Django 5.2.15 on 2026-06-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_produccion_usuario_produccion_nombre_operario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='categoria',
        ),
        migrations.AddField(
            model_name='produccion',
            name='buenas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produccion',
            name='especiales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produccion',
            name='malas',
            field=models.IntegerField(default=0),
        ),
    ]
