# Generated by Django 5.2.15 on 2026-06-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_produccion_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envasado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_operario', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('60', '60'), ('68', '68'), ('120', '120')], max_length=10)),
                ('categoria', models.CharField(choices=[('buena', 'Buena'), ('mala', 'Mala'), ('especial', 'Especial')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
