# Generated by Django 5.2.15 on 2026-06-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_envasado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_operario', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('60', '60'), ('68', '68'), ('120', '120')], max_length=10)),
                ('buenas', models.IntegerField(default=0)),
                ('malas', models.IntegerField(default=0)),
                ('especiales', models.IntegerField(default=0)),
            ],
        ),
    ]
