# Generated by Django 5.2.15 on 2026-06-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_produccion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='tipo',
            field=models.CharField(choices=[('60', '60'), ('68', '68'), ('120', '120'), ('CRISTIx60', 'CRISTIx60')], max_length=10),
        ),
        migrations.AlterField(
            model_name='envasado',
            name='tipo',
            field=models.CharField(choices=[('60', '60'), ('68', '68'), ('120', '120'), ('CRISTIx60', 'CRISTIx60')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='tipo',
            field=models.CharField(choices=[('60', '60'), ('68', '68'), ('120', '120'), ('CRISTIx60', 'CRISTIx60')], max_length=10),
        ),
        migrations.AlterField(
            model_name='palet',
            name='tipo',
            field=models.CharField(choices=[('60', '60'), ('68', '68'), ('120', '120'), ('CRISTIx60', 'CRISTIx60')], max_length=10),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='tipo',
            field=models.CharField(choices=[('60', '60'), ('68', '68'), ('120', '120'), ('CRISTIx60', 'CRISTIx60')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tipo',
            field=models.CharField(choices=[('60', '60'), ('68', '68'), ('120', '120'), ('CRISTIx60', 'CRISTIx60')], max_length=10),
        ),
    ]
