# Generated by Django 5.2.15 on 2026-06-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_despacho_tipo_alter_envasado_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envasado',
            name='fecha',
            field=models.DateField(),
        ),
    ]
