# Generated by Django 5.2.15 on 2026-06-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_envasado_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palet',
            name='cerrado',
        ),
        migrations.AlterField(
            model_name='palet',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='palet',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
