# Generated by Django 6.0.6 on 2026-06-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_palet_cerrado_alter_palet_fecha_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='palet',
            unique_together={('tipo', 'lote')},
        ),
        migrations.AlterField(
            model_name='palet',
            name='lote',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='palet',
            name='fecha',
        ),
    ]
